theme: jekyll-theme-minimal
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!
layout: page
title: "Dataset"
permalink: /dataset/
This dataset is so interesting! Check it out here
This dataset can be used for...
